### ISSUE TITLE
API already working in nextcloud 15 alpha build?

### ISSUE THREAD

**Issue by bbernhard** [e-alfred/ocdownloader#111]
I just stumbled accross ocDownloader and wanted to ask whether there is already an ETA when the stable version for nextcloud 15 will be available? I want to write my own application built upon the ocDownloader API, but if I understood it correctly, the API functionality is currently not working in the recently released alpha version for nextcloud 15? 

Is there anything I can do to help? Unfortunately, I am not (yet) familiar with neither the ocDownload nor the nextcloud sourcecode, but if there is anything I can do to help, please let me know. 

Thanks a lot!

**Comment by e-alfred** [comment]
> I want to write my own application built upon the ocDownloader API

This is awesome news!

> but if I understood it correctly, the API functionality is currently not working in the recently released alpha version for nextcloud 15

Yes, currently there is a problem with the API, but I am not quite sure if it is an ocDownloader bug or a Nextcloud bug:

{"reqId":"XGVj9g2jydFDFFu3iqxs8gAAAA8","level":3,"time":"2019-02-14T13:49:58+01:00","remoteAddr":"1.1.1.1","user":"user","app":"PHP","method":"POST","url":"/owncloud/ocs/v1.php/apps/ocdownloader/api/version?format=json","message":"Error: Call to undefined method Exception::getResult() at /var/www/owncloud/ocs/v1.php#71","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.97 Safari/537.36 Vivaldi/2.4.1455.4","version":"15.0.4.0","id":"5c6563f6a3857"}

> but if there is anything I can do to help, please let me know.

If you could help fix any of the open issues or add a feature this would be highly appreciated!

**Comment by e-alfred** [comment]
The API works now, I will soon create a new release. You can test it already by cloning this repository. The fix is included in this commit: https://github.com/e-alfred/ocdownloader/commit/49dd4afd13f3a58fd591e789d407d10ad09dfa6c

**Comment by e-alfred** [comment]
@bbernhard Can I help you in any other way with creating your app? I would really like to help you out if you need something regarding this.
