### ISSUE TITLE
No personal settings entry with 1.6.1

### ISSUE THREAD

**Issue by OscarXvita** [e-alfred/ocdownloader#114]
### Steps to reproduce
1. nextcloud 15.05
2. download and enable ocdownloader 1.6.1
3. go to settings

### Expected behaviour

ocDownloader user settings should be displayed in settings(personal)->additional.

### Actual behaviour

No "additional" entry for ocDownloader in personal settings, only in admin settings.
Making it unable for user to adjust seeding settings.

### Server configuration

**Operating system**:

**Web server:** Apache2

**Database:** mariadb

**PHP version:** 7.2

**Nextcloud version:15.0.5 (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:updated from 15.0.2

**Where did you install Nextcloud from:** website

**Signing status:**
<details>
<summary>Signing status</summary>

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/ocdownloader/commit/374be75e10cf2723fc376e823dcbc3ddf8f7704b.

I will publish a new release soon.
