### ISSUE TITLE
COPYING vs. LICENSE

### ISSUE THREAD

**Issue by Nibbels** [e-alfred/ocdownloader#12]
Kind of everywhere we have the text:

>  * This file is licensed under the Affero General Public License version 3 or
>  * later. See the **COPYING** file.

But removed COPYING and added **LICENSE**.

**Comment by Nibbels** [comment]
changed in my repo

**Comment by e-alfred** [comment]
It shouldn't be a problem renaming this file. I just used the Github license generator which requires the file to be called that way..

**Comment by Nibbels** [comment]
I like LICENCE! 
It makes sense and I did not rename it.
Adapting is quite easy: I used search and replace on the line and all(?) files should be in sync now.

**Comment by e-alfred** [comment]
COPYING wasn't there before the CC-BY-SA change. He created it after changing to that license. As i took his last AGPL version I had no license file so I created one. Do you mind to create a PR?

**Comment by Nibbels** [comment]
I know some about the github and desktop-client but not all :)
But I think that this change from comment COPYING to comment LICENSE is just one commit which would be pushed if you merge my pull request.

In that case we have to merge it all?
Is it possible to only merge one commit? (To discuss the others whenever there is time and knowledge has increased)

**Comment by e-alfred** [comment]
I will see how it can be done (using `git cherry-pick`), but I think in the future it would be awesome to create multiple smaller PR to make it easier to keep track of changes/discussion.

**Comment by Nibbels** [comment]
Maybe I should make a new branch for every commit.
I will test this when I change something next time.

Same for my issues and discussion: That got a bit unsorted ^^. Too many tabs open and too less knowleged on this state of research while wanting to document everything. I will think about that too. ^^

**Comment by Nibbels** [comment]
https://github.com/e-alfred/ocdownloader/pull/9

closed with https://github.com/e-alfred/ocdownloader/commit/8002cd77b0b0a4003efee1f8d357e860d9c788ac
