### ISSUE TITLE
ocDownloader doesn't consider User Quota 

### ISSUE THREAD

**Issue by Irillit** [e-alfred/ocdownloader#120]
### Steps to reproduce
1.  Set default user quota;
2.  Download more then user quota

### Expected behaviour
Program should check user quota before the download.

### Actual behaviour
It downloads more. For example, I have 11.7 GB with quota 10 GB. And I can download more.

### Server configuration

**Operating system**: Centos 7.5

**Web server:** Apache 2.4.6

**Database:**:  MariaDB 10.3

**PHP version:**: 7.0.33

**Nextcloud version:** (see Nextcloud admin page): 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**: updated from baseline 14.

**Where did you install Nextcloud from:**: from web site archive package. 

I tried on other server - it definetly doesn't check the quota before downloading from site.

I will try to fix it if you don't mind.

**Comment by Irillit** [comment]
It seems for me that before the start of download there is no chance to know the size. So, the download should be suspended or stopped.

**Comment by Irillit** [comment]
It seems I'm almost done with HTTP download and cURL method. 
I found how to check size before the download.
My plan is:
1. Check for a user quota. 
2. Add a method to CURL class that recives only header, where it's possible to see a size.
3. Compare user quota with a file size (in add() method of HttpDownloader. If it's bigger, return error with message "Quota Exceeded".
This plan lacks one thing: quota is updated only when download is completed. So if your quota is 10 Gb, it's possible to start 6 downloads with 5 GB, and it will be finished. So I'm working on special quota inside ocDownloader that will calculate new quota that includes files that are currently downloading .

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/ocdownloader/pull/123. Thank you for your help!
