### ISSUE TITLE
Add proper plural forms and a parameter.

### ISSUE THREAD

**Issue by rakekniven** [e-alfred/ocdownloader#121]
Example:

https://github.com/e-alfred/ocdownloader/blob/4744caf32f1d037b8fe9c19abf5ee8dc38d9e0f0/templates/settings/personal.php#L70

There are some more occurrences.

**Comment by e-alfred** [comment]
Thanks for your help, can you list other places where you found this problem? In the example above I can see a problem with a change to translate plural forms because it is an input field where we don't know the value in advance because the user has to enter it.

**Comment by rakekniven** [comment]
Hello,

see next five lines in the same file.
Understood your explanation. My idea would be to just name the input fields Minutes, Hours, Days, Years.

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/ocdownloader/commit/8b6bd4980d87289528a5fb951efce8b773012a1f

**Comment by rakekniven** [comment]
Great! Thank you

**Comment by e-alfred** [comment]
Now I am just waiting for some translations to publish the next release.

**Comment by rakekniven** [comment]
Hang on :-) German is ready and others will follow soon.
