### ISSUE TITLE
Youtube-dl download prompt can't find GID, http download prompt Not enough free space

### ISSUE THREAD

**Issue by XWolcen** [e-alfred/ocdownloader#124]
"https://github.com/e-alfred/ocdownloader#using-curl-instead-of-aria2"

I have tried the method here, and I also tried to reinstall nextcloud, but the problem still exists. What is the problem? Why is this problem so stubborn!

I manually use the youtube-dl download URL directly in the system and everything works fine. . .
I am going to be tortured crazy. . .

**Comment by e-alfred** [comment]
This could be a problem with this PR: https://github.com/e-alfred/ocdownloader/pull/123

Do you have a quota set for your account? Is the download you try to start bigger than your quota?

**Comment by XWolcen** [comment]
Error | Undefined index: result at /usr/local/nextcloud/apps/ocdownloader/controller/httpdownloader.php#202 |   | 2019-07-13T08:19:15+0800
-- | -- | -- | --
Error | Undefined index: result at /usr/local/nextcloud/apps/ocdownloader/controller/httpdownloader.php#189 |   | 2019-07-13T08:19:15+0800
Error | Undefined index: result at /usr/local/nextcloud/apps/ocdownloader/controller/httpdownloader.php#188 |   | 2019-07-13T08:19:15+0800
Error | Undefined index: result at /usr/local/nextcloud/apps/ocdownloader/controller/httpdownloader.php#183


This is the error log. Where is this incompatible?

**Comment by lyn1337** [comment]
Did you check the permissions for the files in apps/ocdownloader/SERVER/ again? Updates require to fix them, at least for me.

**Comment by e-alfred** [comment]
As there are no replies for a long time now, I will close this issue. If you still face this problem, just add a comment with additional information and we can reopen this issue.

@lyn1337 The Curl downloader is now set as executable by default, so this shouldn't be a problem in future updates anymore.
