### ISSUE TITLE
Add support for Magnet links using Aria2

### ISSUE THREAD

**Issue by e-alfred** [e-alfred/ocdownloader#13]
Aria2 can support this, see:

https://aria2.github.io/manual/en/html/aria2c.html#download-using-bittorrent-magnet-uri

**Comment by Nibbels** [comment]
I saw those type of links the first time in my life today. And didnt know what to do with them.
Bittorrent did not really matter in my previous live. ^^

As I read that is _just a link_ that is an alternative to uploading .torrents.
**Nice!**

**Comment by DJCrashdummy** [comment]
it seems that magnet links where on the list a long time ago: https://github.com/DjazzLab/ocdownloader/issues/17 :wink:

**Comment by programagor** [comment]
Any idea when it is going to be merged into master? As it is right now, the BitTorrent portion is unusable for me without this feature.

**Comment by ThisIsQasim** [comment]
Same here. Would love to see the PR merged.

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/ocdownloader/commit/fd40e036bf27559393e6e2aee9a2eccf2eeca077. Thanks @JasonPoon-cn!

**Comment by LukaPitamic** [comment]
@e-alfred how to implement magnet links being consumed by ocDownloader? I'm new to NC so sorry if the question is dumb. Also how to update NC App?
