### ISSUE TITLE
Launched torrents get added to aria2 queue, but not listed anywhere in ocDownloader

### ISSUE THREAD

**Issue by RussianNeuroMancer** [e-alfred/ocdownloader#132]
### Steps to reproduce
1. Add 20-30 torrents to ocDownloader,
2. Launch downloading of few torrents, wait for download completion 
2. Now launch download for 15-20 more torrents, all at the same time, without waiting for download completion 

### Expected behaviour
Torrents from step 3 get added to list just like torrents from step 2.

### Actual behaviour
When Active Downloads list exceeds ten (or so) following launched torrent downloads no longer added to ocDownloader lists, but get downloaded by aria2 nevertheless. 

### Server configuration

**Operating system**: Armbian 18.04

**Web server:** Apache 2.4.29

**Database:** PostgreSQL 10.10

**PHP version:** 7.2.19

**Nextcloud version:** 16.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** update from Nextcloud 15.

**Where did you install Nextcloud from:** tar from web-site.

**Signing status:** [only this error](https://github.com/nextcloud/server/issues/16294)

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one (currently not supported by ocDownloader):** local folder

**Are you using encryption (currently not supported by ocDownloader):** no

**Are you using an external user-backend, if yes which one:** no

#### ocDownloader configuration:

**Which downloader are you using:** aria2

**Do you use a proxy:** no

**Which protocols do you allow**: FTP/HTTP/Bittorrent/Youtube

### Client configuration
**Browser:** Firefox 69.0.1

**Operating system:** Ubuntu 19.10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Unfortunately, when issue happened I didn't checked Nextcloud log. Nextcloud log appear to be rotated since launching torrent downloads, that caused this issue.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by RussianNeuroMancer** [comment]
This time issue reproduced exactly when eight torrents was seeding and two downloading, and I tried to add another one. So I guess problematic limit is ten torrents.

When issue is reproducible all further torrent downloads is no longer registered by ocDownloader, but aria2c download them anyway. It's just became impossible to remove completed downloads from aria2c via ocDownloader.

**Comment by e-alfred** [comment]
Can you try to reproduce this issue with the latest release? I fixed some things relating to Torrents in the UI.

**Comment by RussianNeuroMancer** [comment]
Issue is not reproducible anymore with 1.7.5. Thank you for fixing this! :)
