### ISSUE TITLE
Update notification setting not working

### ISSUE THREAD

**Issue by jonathanmmm** [e-alfred/ocdownloader#137]
Hello Nextcloud Community,

I am running aria2 1.30.0 which is the newest for Debian Stretch.
I am running php 7.3 and nginx.

If I choose to select 
Check for updates ? NO in Admin -> Settings -> Additional settings
It does not work.

As a user (or admin, does not matter) I still see the following
![image](https://user-images.githubusercontent.com/32403139/67878009-ea5ab980-fb3a-11e9-9b5a-1a16cf827260.png)

Probably because the newest version of aria2 is 1.35.0 (under sid branch in debian).

Is this correct, that this banner should go away?
If I click the download button it downloads the newest version of the ocdownloader App as master.zip.

Under nextclouds apps I can see that I have installed 1.7.3 of ocdownloader (which is the newest right now).

So is this searching for a newer aria2 version or app version?
And is this a bug or what is this setting doing?

**Comment by e-alfred** [comment]
This is a deprecated component that got finally removed with release 1.7.4.
