### ISSUE TITLE
When switching to active downloads, the server crashes.

### ISSUE THREAD

**Issue by letopisec3** [e-alfred/ocdownloader#138]
1. Apche 2.4
2. Php 7.2
3. MariaDB
4. Nextcloud 17.0.1

When switching to active downloads, the server crashes
`	ParseError: syntax error, unexpected '<', expecting end of file

    /hdd/home/web/nextcloud/lib/private/Template/Base.php - line 150:

    OC\Template\Base->load("/hdd/home/w ... p", { PAGE: 3,CA ... "})

    /hdd/home/web/nextcloud/lib/private/legacy/template.php - line 180:

    OC\Template\Base->fetchPage({ PAGE: 3,CA ... "})

    /hdd/home/web/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php - line 165:

    OC_Template->fetchPage({ PAGE: 3,CA ... "})

    /hdd/home/web/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 123:

    OCP\AppFramework\Http\TemplateResponse->render()

    /hdd/home/web/nextcloud/lib/private/AppFramework/App.php - line 126:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\ocDownlo ... {}, "Actives")

    /hdd/home/web/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("IndexController", "Actives", OC\AppFramew ... {}, { _route: "o ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "o ... "})

    /hdd/home/web/nextcloud/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "o ... "})

    /hdd/home/web/nextcloud/lib/base.php - line 1000:

    OC\Route\Router->match("/apps/ocdownloader/actives")

    /hdd/home/web/nextcloud/index.php - line 42:

    OC::handleRequest()`

One more question, how can a torrent be paused?

**Comment by e-alfred** [comment]
Fixed with https://github.com/e-alfred/ocdownloader/commit/c7bee750870827a9dbe9eeff5e42771dcd6d882e, thanks for reporting!

I will publish a new release that fixes both things you asked about.
