### ISSUE TITLE
Personal settings for group admins in NC17 not accessible using ocDownloader

### ISSUE THREAD

**Issue by AleksCee** [e-alfred/ocdownloader#140]
There is a description in the nextCloud issue to this I figure out:
https://github.com/nextcloud/server/issues/17899#issuecomment-555537594

If I disable ocDownloader the personal settings are accessible for all, if the app is active, group admins can’t go to there personal settings page.

**Comment by Morganlej** [comment]
Confirming. When ocDownloader is enabled, a group admin wanting to see settings thecloud/index.php/settings/user gets instead thecloud/index.php/apps/files/

NexCloud version 17.0.0.9, ocDownloader 1.7.5

**Comment by clawoflight** [comment]
Same for me.

**Comment by Saroufim** [comment]
I can confirm the same issue is occuring with me on NextCloudPi. I had to relinquish my group administrator rights to be able to access my settings.

**Comment by noci2012** [comment]
The checkAdminUser call redirects the settings page to de default /apps/files page.
Which is not desirable. (Nextcloud 17+ behaviour combined with groupadmin ).

Solution: Either disable the offending app or
See here for the solution:
nextcloud/server#18865

in this case: apps/ocdownloader/settings/admin.php
```
+if (!OC_User::isAdminUser(OC_User::getUser())) {
+   return;
+}
-User::checkAdminUser();
```
t/y.

**Comment by e-alfred** [comment]
@noci2012 Thanks for your help! Can you create a PR that fixes this issue?

**Comment by noci2012** [comment]
Done

**Comment by e-alfred** [comment]
I merged the fix by @noci2012 and will make a new release soon. Thanks for your help!
