### ISSUE TITLE
After installation, ocdownloader fails when folder "Downloads" is not existing

### ISSUE THREAD

**Issue by Wikinaut** [e-alfred/ocdownloader#142]
When the designated download folder is not existing, ocdownloader creates a file "Downloads" and of course fails then to download a file from an Url.

* ocdownloader using curl
* NC 17.0.1
* ocdownloader 1.7.5
* php 7.3.11
* Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux

**Comment by e-alfred** [comment]
This is a duplicate of https://github.com/e-alfred/ocdownloader/issues/42.
