### ISSUE TITLE
Fehler, GID nicht gefunden!

### ISSUE THREAD

**Issue by geeflaxx** [e-alfred/ocdownloader#143]
### Steps to reproduce
1. install ocdownloader via nextcloud app
2. apt-get install python-pip
   pip install youtube-dl
3. use CURls

### Expected behaviour
i want download a youtube video
but i get an error that the GID is'nt found.

### Server configuration

**Operating system**:
nextcloud 17.01
**Web server:**
apache
**Database:**
maria
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
17.01
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
raspbian -> sudo apt install nextcloud..

**Comment by e-alfred** [comment]
Did you follow the instructions on how to set up CURL? You have to install the appropriate packages and make the files in the SERVER directory executable:

https://github.com/e-alfred/ocdownloader#using-curl-instead-of-aria2

**Comment by GAS85** [comment]
Sorry, my mistake, after Application was removed and installed again I forgot about this command:

    chmod +x /var/www/nextcloud/apps/ocdownloader/SERVER/fallback.*

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/ocdownloader/commit/55a00e9651e3968a7b793cd79a80d2537fed68e4, finally.
