### ISSUE TITLE
how to download via Magnet Link?

### ISSUE THREAD

**Issue by saketkoria** [e-alfred/ocdownloader#145]
### Steps to reproduce
1. Downloaded latest ocDownloader from App store of Nextcloud
2. Where to add the magnet link
3.

### Expected behaviour
Magnet link show be allowed to add

### Actual behaviour
only option is to select torrent file

### Server configuration

**Operating system**: nextcloud  on Raspberry pi 4
*

**Nextcloud version:** 

NextCloudPi 17.0.1

PHP version
Version: 7.3.4

Memory Limit: 693.4 MB

Max Execution Time: 3600

Upload max size: 10 GB

** fresh install:**

**Where did you install Nextcloud from:* RPI4 Image

#### ocDownloader configuration:

**Which downloader are you using:** Curl/Aria2

**Do you use a proxy:** No

**Which protocols do you allow**: FTP/HTTP/Bittorrent/Youtube

**Comment by LucasJavaudin** [comment]
I was looking for a magnet link too but I think that there is none. I think that you are supposed to use your magnet link under the HTTP tab, similarly to a regular download link. It worked great for me.

**Comment by saketkoria** [comment]
Thanks Lucas
Will try for that

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/ocdownloader/commit/937a4eb383f945eb8588a03eb1a7420fc37bfa63
