### ISSUE TITLE
GID null error with NC 17.0.2

### ISSUE THREAD

**Issue by z0ow** [e-alfred/ocdownloader#147]
### Steps to reproduce
1. Enable ocDownloader in Nextcloud Application Page
2. Run aria2 as www-data
3. Upload torrent to launch download task

### Expected behaviour
Task up normally

### Actual behaviour
ocDownloader alert message `Returned GID is null ! Is Aria2c running as a daemon ?`
by the way, a torrent name same directory has been created in Downloads/
(firewall-cmd --list-all show the aria2 port 6800 is open, and ocdl is still work normally yesterday, that so weird)
### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache 2.4

**Database:** MySQL 5.7.28

**PHP version:** 7.3.13

**Nextcloud version:** (see Nextcloud admin page) 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - apporder: 0.9.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - camerarawpreviews: 0.7.2
  - checksum: 0.4.3
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - data_request: 1.4.0
  - dav: 1.13.0
  - dicomviewer: 1.2.1
  - drawio: 0.9.4
  - event_update_notification: 1.0.0
  - extract: 1.2.2
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_markdown: 2.1.0
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.6.0
  - files_readmemd: 1.1.3
  - files_retention: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocdownloader: 1.7.5
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - qownnotesapi: 19.9.0
  - quota_warning: 1.6.0
  - ransomware_detection: 0.6.0
  - ransomware_protection: 1.5.1
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - workflow_pdf_converter: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - audioplayer
  - encryption
  - files_external
  - files_videoplayer
  - metadata
  - onlyoffice
  - passwords
  - richdocuments
  - support
  - user_ldap
  - viewer
  - w2g2
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "default_language": "zh_CN",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.100.252:8001",
        ],
        "skeletondirectory": "\/home\/www-data\/ServerData\/nextcloud_skeleton",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "data-fingerprint": "63de176b8a61716b79f61569d1556a90",
        "app_install_overwrite": [
            "bookmarks_fulltextsearch"
        ]
    }
}
</details>

**Are you using external storage, if yes which one (currently not supported by ocDownloader):**  no

**Are you using encryption (currently not supported by ocDownloader):**  no

**Are you using an external user-backend, if yes which one:** no

#### ocDownloader configuration:

**Which downloader are you using:** Aria2

**Do you use a proxy:** No

**Which protocols do you allow**: FTP/HTTP/Bittorrent/Youtube

##### Aria2c error log
<details>
<summary>Aria2c log file (set the log level to debug by using --log-level=debug)</summary>
2019-12-30 14:40:08.785932 [DEBUG] [HttpServer.cc:296] HTTP Server sends response:
HTTP/1.1 400 Bad Request
Date: Mon, 30 Dec 2019 06:40:08 GMT
Content-Length: 136
Expires: Mon, 30 Dec 2019 06:40:08 GMT
Cache-Control: no-cache
Content-Type: application/json-rpc
Access-Control-Allow-Origin: *
Connection: close

2019-12-30 14:40:08.786013 [INFO] [AbstractHttpServerResponseCommand.cc:118] CUID#10 - HttpServer: all response transmitted.
</details>

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10 

#### Web server error log
<details>
<summary>Web server error log</summary>
No error output in web server.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
No error/warning output after operation
</details>

#### Browser log
<details>
<summary>Browser log</summary>
No any error log in console.
</details>

**Comment by e-alfred** [comment]
How do you run Aria2? Did you run it as advised by the readme:

https://github.com/e-alfred/ocdownloader#aria2-installation

Can you download other files like HTTP/FTP links?

**Comment by ZehuanZhang** [comment]
> How do you run Aria2? Did you run it as advised by the readme:
> 
> https://github.com/e-alfred/ocdownloader#aria2-installation
> 
> Can you download other files like HTTP/FTP links?

So sorry to be so late reply to you, I have tried to re-install aria2 by this LINK but my OCDownloader still alerts 'Returned GID is null'. In my case, the HTTP/FTP links only can be download when the downloader is cURL. By the way, the aria2c.log shows nothing when I got GID Error message:

```
$ cat /var/log/aria2c/aria2c.log 
2019-12-30 12:09:30.438414 [WARN] [DownloadEngineFactory.cc:201] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.
2019-12-30 12:25:28.949973 [WARN] [DownloadEngineFactory.cc:201] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.
2020-04-24 22:25:36.579237 [WARN] [DownloadEngineFactory.cc:201] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.
```

**Comment by weeman1337** [comment]
@e-alfred since ocdownloader only supports NC19+ in the current version maybe this one could be closed?

**Comment by z0ow** [comment]
Yes, thanks
