### ISSUE TITLE
Aria2c and cURL configuration

### ISSUE THREAD

**Issue by Andreas-Kainz** [e-alfred/ocdownloader#148]
Hi,

as I remember cURL support
- http
- ftp

aria2 support 
- http
- ftp
- bittorrent

and youtube-dl support
- youtube/stream download

as for some hosters you didn't have aria2 and youtube-dl accessible, would it be possible to define an fallback strategy instead of `Returned GID is null ! Is Aria2c running as a daemon ?` the app use curl for the http download and don't offer bittorrent support (as long as aria2c is not working correct)

**Comment by DarkknightAK** [comment]
In addition an settings section in the sidebar (like you know from the files sidebar at the bottom) where you can configure stuff like aria2, update youtube-dl, ... define proxy, force ipv4 connection, ... would be nice so you don't have to offer technical stuff in the UI of the app.

**Comment by e-alfred** [comment]
@DarkknightAK Well those settings are individual for each download so they should be directly accessible below the download link input field.

As for having a fallback, this is not so easy to achieve because the files have to be downloaded directly into the Nextcloud folder at the moment. If somebody can contribute something in that regard any help is highly welcome.

**Comment by DarkknightAK** [comment]
I do icon design in open source projects and UI stuff. If you need something let me know.

**Comment by DarkknightAK** [comment]
Thanks for the feedback

**Comment by e-alfred** [comment]
No problem, If you like to help out there are still a few things open like support for Dark Mode and a mobile view or a new background image for the ocDownloader browser extensions:

https://github.com/e-alfred/ocDownloader_webextension/issues/4
https://github.com/e-alfred/ocdownloader/issues/131
https://github.com/e-alfred/ocdownloader/issues/95

**Comment by e-alfred** [comment]
You can run a Aria2c on a remote host now, so this could help with your problem: https://github.com/e-alfred/ocdownloader/pull/164
