### ISSUE TITLE
Add support for NC 18

### ISSUE THREAD

**Issue by bekon16** [e-alfred/ocdownloader#150]
Hi,

Is this version compatible with NC18?
https://apps.nextcloud.com/apps/ocdownloader - the last one here is only 17.

Cant upgrade without ocDownloader :)

**Comment by e-alfred** [comment]
This line of code currently breaks ocDownloader on Nextcloud 18: https://github.com/e-alfred/ocdownloader/blob/f5f4ae92140b4801a7a4f7df642d46032e9d8566/controller/index.php#L247

**Comment by e-alfred** [comment]
Fixed by @mamartel, I will publish a new release soon.
