### ISSUE TITLE
Download freeze on waiting status with curl

### ISSUE THREAD

**Issue by pedrxd** [e-alfred/ocdownloader#155]
### Steps to reproduce
1. Install OcDownloader
2. Change from aria2 to curl
3. Try to download a file

### Expected behaviour
Get a file correctly downloaded. 
OcDownloader should create a Downloads **folder** on the root directory before download

### Actual behaviour
The download get waiting status and doesn't do nothing
OcDownloader create a **file** on the root directory before download

### How to solve
Remove the file created and create a new folder with Downloads as name.

### Server configuration

**Operating system**:
Debian10
**Web server:**
Nginx-fpm
**Database:**
Mariadb
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 17
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from older nextcloud
**Where did you install Nextcloud from:**
Installed using docker

**Comment by CptDayDreamer** [comment]
Same here. Are you using nginx as reverse-proxy? Maybe we have to add some proxy settings or something. I'm not so known in proxy stuff.

**Comment by bitsandnumbers** [comment]
I have a similar issue.

The status is in "waiting" on OCD side, but the file is actually fully downloaded in Downloads folder.

Nextcloud Docker 18.0.1
OCDownloader 1.7.6
PHP 7.3
Curl + Php-Curl compiled from sources (doesn't work at all without it)

**Comment by e-alfred** [comment]
This seems to be a Docker related (at least with the Nextcloud Docker container) problem. On normal installations without Docker there should be absolutely no need to compile anything PHP or Curl related yourself.

**Comment by bitsandnumbers** [comment]
@e-alfred I used the usual `docker-php-ext-install` binary to install the php-curl extension, which compiles php-curl. It's the only way to add php extension from inside a docker container. What I meant is that `php -m` in a fresh NC docker container show that curl extension is already there. But even then, OCD does not work. From there, `docker-php-ext-install curl` re-install (compile) the Curl extension again, and then OCD actually work partially with curl (as stated above). I didn't investigate further to understand what the re-install would add from vanilla php-curl though.

**Comment by pedrxd** [comment]
After update to nextcloud 18 the problem dissapear (docker version nextcloud:18-fpm)

**Comment by mgrddsj** [comment]
This seems not to be a docker related problem. I just installed ocDownloader, chose to use cURL, and it creates a file called "Downloads", but not a folder. 

It seems to be a problem when the folder "Downloads" doesn't exist, and ocDownloader tries to create a **file** called "Downloads", where it should create a folder called "Downloads". 

I manually deleted the "Downloads" file and created a folder called "Downloads" as described by @pedrxd and it worked fine. 

Server configuration
Operating system:
Debian 10 (DietPi)
Web server:
Nginx-fpm 
Database:
mysql
PHP version:
7.3.15 
Nextcloud version: (see Nextcloud admin page)
Nextcloud 18.0.3
Updated from an older Nextcloud/ownCloud or fresh install:
Updated from older nextcloud
Where did you install Nextcloud from:
Installed directly (not in docker)

**Comment by tustunkok** [comment]
The solution does not work for me. I am running Nextcloud 21 in a docker container with PHP-fpm, MariaDB 10.5 with the addition of an Nginx reverse-proxy out on host (without docker).

All youtube downloads start in waiting state despite the downloads folder created beforehand.

**Comment by weeman1337** [comment]
There has been an issue setting a curl option. Should be improved with the next release. Please feel free to report back if it doesn't work.
