### ISSUE TITLE
When switching to active tabs, the server crashes

### ISSUE THREAD

**Issue by letopisec3** [e-alfred/ocdownloader#156]
Apche 2.4
    Php 7.2
    MariaDB
    Nextcloud 18.0.1

`
[index] Error: Exception: Argument 3 passed to OC\Files\Utils\Scanner::__construct() must implement interface OCP\EventDispatcher\IEventDispatcher, instance of OC\Log given, called in /hdd/home/web/nextcloud/apps/ocdownloader/controller/index.php on line 247 at <<closure>>

0. /hdd/home/web/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\ocDownloader\Controller\Index {}, "Stopped")
1. /hdd/home/web/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("IndexController", "Stopped", OC\AppFramework\ ... {}, {_route: "ocdownloader.Index.Stopped"})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "ocdownloader.Index.Stopped"})
3. /hdd/home/web/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {_route: "ocdownloader.Index.Stopped"})
4. /hdd/home/web/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/ocdownloader/stopped")
5. /hdd/home/web/nextcloud/index.php line 38
   OC::handleRequest()

GET /index.php/apps/ocdownloader/stopped
from 212.3.131.164 by letopisec at 2020-03-04T18:26:57+00:00
`

**Comment by e-alfred** [comment]
This problem was fixed with the latest release, did you update to 1.7.6?

**Comment by letopisec3** [comment]
Market in version 1.7.5.
After updating from github to version 1.7.6, the problem was solved.
Ty, problem solved
