### ISSUE TITLE
Set RPC Secret

### ISSUE THREAD

**Issue by Happyfeet01** [e-alfred/ocdownloader#166]
Hello,

Mentioned in this issue https://github.com/e-alfred/ocdownloader/pull/164 it’s possible to set the RPC secret. We’re can I do this? I have no settings for this in the ocdownloader settings.

**Comment by e-alfred** [comment]
I will have to make a new release that includes this feature, if you want to test it now you can clone the repository to get it.

**Comment by Happyfeet01** [comment]
It works :-)

**Comment by e-alfred** [comment]
Version 1.7.8 was released to the app store. Have fun!

**Comment by ShuminKong** [comment]
Still not setting for this. I'm on 1.7.8.

**Comment by Happyfeet01** [comment]
Sure under /settings/admin/additional

**Comment by e-alfred** [comment]
It should be available here:

![image](https://user-images.githubusercontent.com/10073629/83979087-1083db80-a90c-11ea-8502-ba70172f1cf1.png)

**Comment by ShuminKong** [comment]
Still no. I am on the latest Nextcloud 19, is this an issue?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by e-alfred** [comment]
Did you clean your browser cache? Can you try to remove the app and reinstall it?

**Comment by ShuminKong** [comment]
Still no. I am happy to provide debug info that you need.
