### ISSUE TITLE
--log=/var/log/aria2.log -> Logfiles get huge!

### ISSUE THREAD

**Issue by Nibbels** [e-alfred/ocdownloader#17]
![screenshot_1](https://user-images.githubusercontent.com/3265671/29780705-02909e88-8c17-11e7-90bf-73c25eb10d2b.png)

I downloaded a torrent with about 8gb. (And tested around some bit.)
Centos 7 full iso.
Afterwards i saw that the Iso got that really huge.

**Comment by e-alfred** [comment]
You could try to set `log-level=warn` as shown here:

https://wiki.archlinux.org/index.php/aria2#Example_aria2.conf

Aside from that, logrotate might be another useful tool against huge logfiles.

**Comment by Nibbels** [comment]
Yes, just to have it documented. I guess we can close this.
I removed the switch for me - as long as aria2 works. So the tempfile stays at 0byte
