### ISSUE TITLE
[youtubedl]download video by ocdownloader ,videos has no sound

### ISSUE THREAD

**Issue by xspeed1989** [e-alfred/ocdownloader#174]
### Steps to reproduce
install ffmpeg
install youtube-dl
manual download:   youtube-dl -f bestvideo+bestaudio https://www.youtube.com/watch?v=wUJ-57SAE5A
the video has sound

but i download the same url with ocdownloader ,the video has no sound
download youtube by aria2 is slow than by youtube-dl self
@e-alfred

**Comment by e-alfred** [comment]
It seems like your settings aren't correct. it should be `bestaudio[abr<=75]` and `best[width<=1280]`, otherwise you stumble into this problem: https://github.com/e-alfred/ocdownloader/issues/29

**Comment by xspeed1989** [comment]
Thanks
I think use youtube-dl to download is the best way, but you need to calc the progress
It may be a hard work?
@e-alfred

**Comment by Derkades** [comment]
I got the same issue. Settings:
![image](https://user-images.githubusercontent.com/15892014/96641159-984f0d00-1324-11eb-9e1a-a414d7463588.png)
Produces a file with video track only, no audio.

Running the command manually works: `youtube-dlc -f "bestvideo[ext=webm]+bestaudio[ext=webm]" <url>`

**Comment by e-alfred** [comment]
@Derkades @xspeed1989 Please set the Audio and Video format to `bestaudio[abr<=75]` and `best[width<=1280]` as said above.

**Comment by jsellin78** [comment]
is it possible to change format to mp3 instead of bestaudio?
