### ISSUE TITLE
GID not found for Magnet after restart of aria2c

### ISSUE THREAD

**Issue by berlin2123** [e-alfred/ocdownloader#175]
# Steps to reproduce
1.  add several Magnet url to download,
2. after some Magnet urls are downloading and some not,
3.  restart the aria2c or restart the system or after power lose, those Magnet urls which begun to download (now mark as "TORRENT") show "Error, GID not found !".  However those not begun to download (still mark as "MAGNET") can get GID, and show status.

### Expected behaviour
Show the status of downloading for downloaded Magnet.

### Actual behaviour
 Error, GID not found !

It works fine before restart the aria2c, however GID not found after restart.

Other PROTOCOLs  ( such as BitTorrent ) still work fine after the restart of aria2c.

### Server configuration

**Operating system**:
centos 8
**Web server:**
apache 2.4
**Database:**
Ver 15.1 Distrib 10.3.17-MariaDB
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
18,0,7

**Comment by Chion82** [comment]
Having the same problem here.

It looks like the GIDs for downloading Magnet tasks will change after aria2 is restarted, whereas those for the Magnet meta tasks which haven't started downloading yet remain the same.

I've created a [temporary fix](https://github.com/e-alfred/ocdownloader/compare/master...Chion82:master) for this problem. The initial Magnet meta task remains in the queue even if it's completed. After aria2 is restarted, this original meta task will be used to trace any associated downloading tasks with GIDs changed.

**Comment by berlin2123** [comment]
Hi Chion, Thanks a lot.
I don't know how to replace the codes in your "temporary fix".  I will be waiting for the official upgrade.

**Comment by berlin2123** [comment]
I am using github for the first time.

It seems that we need to wait until the code-change is verified before closing issues. I will reopen it now.
