### ISSUE TITLE
HTTP without aria2

### ISSUE THREAD

**Issue by devnull4242** [e-alfred/ocdownloader#178]
Hi,
i do not have installed aria2 and can not install it on my nextcloud.
I am not able to use ocdownloader on my nextcloud.

Can you implement HTTP without aria2?

I think it is possible see the program "Tiny File Manager":
https://github.com/prasathmani/tinyfilemanager

**Comment by e-alfred** [comment]
You can use Curl to download using HTTP/FTP/Youtube-dl: https://github.com/e-alfred/ocdownloader#using-curl-instead-of-aria2
