### ISSUE TITLE
Nextcloud 20 Compatibility

### ISSUE THREAD

**Issue by sunjam** [e-alfred/ocdownloader#182]
Thanks for considering Nextcloud 20 Compatibility

**Comment by nokoa77** [comment]
Hi, +1, it would be great ! Did someone try to force install with NC 20 ? Is it working ? Thanks

**Comment by sunjam** [comment]
Yeah, it works when forced

**Comment by mzramna** [comment]
i've tested,but does not show the remote server setup for aria2 in latest nextcloud until now,only the option to select between curl and aria2

**Comment by e-alfred** [comment]
Fixed by the new release of 1.7.9.
