### ISSUE TITLE
Hovereffect in the menu doesn't use the full width

### ISSUE THREAD

**Issue by marissa999** [e-alfred/ocdownloader#185]
### Steps to reproduce
1. Open the app
2. Hover over the menu

### Expected behaviour
Tell us what should happen
The hover effect uses the full width

### Actual behaviour
Tell us what happens instead
The hover effect only applies to where the text is bc the element itself doesnt use the full width of the sidebar

### Server configuration

**Operating system**:
LXC Container (Debian)

**Web server:**
Nginx

**Database:**
MySQL

**PHP version:**
7.3.19-1~deb10u1

**Nextcloud version:** (see Nextcloud admin page)
20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes, from older version

**Where did you install Nextcloud from:**
Archive from the nextcloud page

**Comment by marissa999** [comment]
Currently:
![Screenshot from 2020-10-17 16-14-24](https://user-images.githubusercontent.com/8284445/96339778-fb2b7480-1096-11eb-8ee8-4b1a5e7cc539.png)
But adding width: 100%; to https://github.com/e-alfred/ocdownloader/blob/b3e26b85d4cbeea4b9a9dd0c4f9c3ed22014e58e/css/styles.css#L38 changes it to this:
![Screenshot from 2020-10-17 16-14-41](https://user-images.githubusercontent.com/8284445/96339797-139b8f00-1097-11eb-986d-1fe069e4da14.png)
This looks much better in my personal opinion. 
I already made a PR which adds this to both the styles.css and styles.min.css. 
https://github.com/e-alfred/ocdownloader/pull/184

**Comment by e-alfred** [comment]
Fixed by #184. Thanks for your help!
