### ISSUE TITLE
Creating YT-DL plugin and other plugins for ocdownloader

### ISSUE THREAD

**Issue by blackcrack** [e-alfred/ocdownloader#188]
### Steps to reproduce
1. open Github
2. search Youtube-DL sources
3. Error , RIAA have told Microsoft, the sourcecode to delete... well, this ground is now in the States..
  
https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md  

https://github.com/ytdl-org/youtube-dl
  
  
### Expected behaviour  
Tell us what should happen  
no trubles  
plugins for put ocdownloader-php-plugins in an own folder under /apps/ocdownloader/plugins
  
### Actual behaviour
Tell us what happens instead
Trubles  
and no plugins for ocdownloader
  
### Server configuration  
**Operating system**: Fedora  
**Web server:** Apache  
**Database:** Mariadb  
**PHP version:** 7.3  
**Nextcloud version:** (see Nextcloud admin page) 18  
**Updated from an older Nextcloud/ownCloud or fresh install:** -  
**Where did you install Nextcloud from:** -  

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

and I bet that won't be the last

fave fun !

**Comment by basxto** [comment]
The youtube-dl on github is disabled, not deleted.
It’s still on pypi and there are updates.

**Comment by blackcrack** [comment]
i have read the news in the last days :+1:

**Comment by e-alfred** [comment]
It is back now: https://github.com/ytdl-org/youtube-dl

ocDownloader is just a frontend for youtube-dl so it is up to the user if they want to install it.

**Comment by weeman1337** [comment]
This issue looks solved to me. If not feel free to post a comment.
