### ISSUE TITLE
Fix downloads not showing up in Nextcloud using Curl

### ISSUE THREAD

**Issue by e-alfred** [e-alfred/ocdownloader#19]
Successful downloads using Curl and youtube-dl don't show up in Nextcloud, but are stored on the filesystem. This should be solved by adapting the patch for Aria2 by @Nibbels.

**Comment by e-alfred** [comment]
Well, the problem with that is the scenario where somebody clicks onto a link to the file in the download list below the download type selection/link box. Without a reload, the files wouldn't be shown in the Nextcloud files app.

**Comment by Nibbels** [comment]
we might just be able to put the scan function into the function where the queue is refreshed.
So any user has his files refreshed whenever he sees them.

We would then scan the files every 2s or so while the browser is opened, but I guess this is not to expensive on performance. At least on my side/server the pages loads quite fast. When anyone would have 3000 files downloaded this might take its while. But not in normale use.

If we wantet to, we could do a test-scan on a bunch of files and measure the time.

Reeeally nice would be to have the folder scanned when entering it. But I guess there is no hook for an app when entering a folder?
That would be like folders.controllerhook.entering.ocdownloader("If entered downloads then scan".)
At the moment I cannot understand or know if such is possible at all...

**Comment by e-alfred** [comment]
Maybe  `\OC\Files\Filesystem::touch($result . $path);` could be of interest to add files to the filecache?

Here are some more examples:

https://hotexamples.com/examples/oc.files/Filesystem/touch/php-filesystem-touch-method-examples.html

**Comment by Nibbels** [comment]
/httpdocs/lib/private/Files/Filesystem.php ?
```
	static public function touch($path, $mtime = null) {
		return self::$defaultInstance->touch($path, $mtime);
	}
```
Is that calling the standard php function?
http://php.net/manual/de/function.touch.php
http://php.net/manual/en/function.touch.php
or an internal function also called touch?

**Comment by Nibbels** [comment]
ok... This is something:
/httpdocs/lib/private/Files/Cache/Scanner.php

> 	 * scan a single file and store it in the cache

> 	public function scanFile($file, $reuseExisting = 0, $parentId = -1, $cacheData = null, $lock = true) {

**Comment by e-alfred** [comment]
Youtube download aren't a problem because they are downloaded by Aria2 and youtube-dl is only used for extraction of the real Youtube URL and audio files. But this implementation is related to this problem: https://github.com/e-alfred/ocdownloader/issues/18

I changed the title accordingly.

**Comment by blackcrack** [comment]
tip: Freedownloader, Alex have solved some problem, he have write a own routine, maybe it's a own binary with the same api's beneficial. would maybe not bad if you ask Alex2000 directly, 
how can make this possible.., by the way can he maybe support ocdownloader, 
if the way open for netbooks and handy's (and handy's who give for notebooks a wlan) if some peoples jetset around the world like Biologists Chemists and some for get the download to ocdownloader drectly to be save ... and Alex have a high experiences in download  ;) Freedownloader and ocdownloader would be a really pretty well pack ;)

best regards
Blacky

**Comment by DJCrashdummy** [comment]
@blackcrack at least i have no idea what you are talking about (https://github.com/e-alfred/ocdownloader/issues/19#issuecomment-326784939)...
it would be nice if you can add some links to the project/devs you are talking about or mention/ping them direct if they are on github.
...and are you sure this is on topic?

**Comment by blackcrack** [comment]
@DJCrashdummy forget it .. i be tired, and was only a idea ..
