### ISSUE TITLE
With the Nextcloud-Versions update an General Versions update ?

### ISSUE THREAD

**Issue by blackcrack** [e-alfred/ocdownloader#2]
hi, it is not on the time 
to have a version 1.5.2 ? (because the support if Nextcloud 12 )

best regards
Blacky

**Comment by e-alfred** [comment]
It is just changing the number in the info.xml file, after all. Should be fixed now.

**Comment by blackcrack** [comment]
jeahey :) thy :)

**Comment by Nibbels** [comment]
I completely moved to this branch now. The old fork had to be deleted to achieve this.

```
Nibbels/ocdownloader
forked from e-alfred/ocdownloader
```
