### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by sunjam** [e-alfred/ocdownloader#201]
Related to #200 nc21 has introduced PHP 8 support.  7.x support will continue for the time being.

**Comment by weeman1337** [comment]
According to the docs NC21 doesn't support PHP 8 yet:  
https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html

**Comment by weeman1337** [comment]
I will have a look at this one soon. ocdownloader supports NC 20 - 22. That means PHP 7.2 - 8.0 should be supported.

Did anyone encouter a problem so far?

**Comment by EWouters** [comment]
Seems to work for me with PHP8.0

**Comment by weeman1337** [comment]
Works for me. If you encounter any issues feel free to report back here.
