### ISSUE TITLE
ocDownloader doesn´t run with NC 21

### ISSUE THREAD

**Issue by tonyblue2** [e-alfred/ocdownloader#203]
### Steps to reproduce
1. I had a running Installation with NC 20.8 and ocDownloader
2. Now I upgraded NC to Version 21
3. Now after click on ocDownloader I got the error message: 
Interner Serverfehler

Der Server konnte die Anfrage nicht fertig stellen.

Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.
Technische Details

    Entfernte Adresse: 188.193.128.180
    Anfragekennung: Aj0Hy9rAsOyJ4W6YwIjv

### Expected behaviour
ncDownloader should run under NC21.

### Actual behaviour
I got tthis message in the error log:

Error | index | Exception: Call to a member function is_dir() on null/var/www/nextcloud/lib/private/AppFramework/App.php - line 157: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 993: OC\Route\Router->match()/var/www/nextcloud/index.php - line 37: OC::handleRequest()Verursacht durchError: Call to a member function is_dir() on null/var/www/nextcloud/apps/ocdownloader/controller/index.php - line 250: OC\Files\Filesystem::is_dir()/var/www/nextcloud/apps/ocdownloader/controller/index.php - line 90: OCA\ocDownloader\Controller\Index->syncDownloadsFolder()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 218: OCA\ocDownloader\Controller\Index->add()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 127: OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 157: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/nextcloud/lib/base.php - line 993: OC\Route\Router->match()/var/www/nextcloud/index.php - line 37: OC::handleRequest()
-- | -- | --

### Server configuration

**Operating system**:
Ubuntu 20.04.2 LTS

**Web server:**
apache

**Database:**
mysql 10.3.25

**PHP version:**
PHP Version 7.4.3

**Nextcloud version:** (see Nextcloud admin page)
21

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 20.8

**Where did you install Nextcloud from:**
zip-file

**Signing status:**
<details>
<summary>Signing status</summary>

```

Error | documentserver_community | OCA\DocumentServer\Document\DocumentConversionException: namespace error : Namespace prefix wp14 on sizeRelH is not defined /drawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"                                                                                ^ namespace error : Namespace prefix wp14 on pctWidth is not defined /main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth                                                                                ^ namespace error : Namespace prefix wp14 on sizeRelV is not defined p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"                                                                                ^ namespace error : Namespace prefix wp14 on pctHeight is not defined wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight                                                                                ^ /var/www/nextcloud/apps/documentserver_community/lib/DocumentConverter.php - line 125: OCA\DocumentServer\Document\ConverterBinary->run()/var/www/nextcloud/apps/documentserver_community/lib/DocumentConverter.php - line 80: OCA\DocumentServer\DocumentConverter->runCommand()/var/www/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php - line 156: OCA\DocumentServer\DocumentConverter->saveChanges()/var/www/nextcloud/apps/documentserver_community/lib/LocalAppData.php - line 102: OCA\DocumentServer\Document\DocumentStore->OCA\DocumentServer\Document\{closure}("*** sensiti ... *")/var/www/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php - line 176: OCA\DocumentServer\LocalAppData->getReadWriteLocalPath()/var/www/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php - line 58: OCA\DocumentServer\Document\DocumentStore->saveChanges()/var/www/nextcloud/apps/documentserver_community/lib/BackgroundJob/Cleanup.php - line 71: OCA\DocumentServer\Document\SaveHandler->flushChanges()/var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 80: OCA\DocumentServer\BackgroundJob\Cleanup->run()/var/www/nextcloud/cron.php - line 128: OCP\BackgroundJob\Job->execute()
-- | -- | --



```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - calendar: 2.1.3
  - carnet: 0.23.8
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.3.1
  - documentserver_community: 0.1.9
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_markdown: 2.3.3
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - groupfolders: 9.0.0
  - imageconverter: 1.3.1
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.9.3
  - maps: 0.1.8
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - ocdownloader: 1.7.10
  - onlyoffice: 6.3.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.1.1
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - unsplash: 1.2.1
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - encryption
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.0.18",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "trusted_domains": [
            "localhost",
            "192.168.3.201",
            "firstcloud.dynvpn.de",
            "192.168.3.200"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "logfile": "\/var\/www\/nextcloud\/data\/nextcloud.log",
        "syslog_tag": "Nextcloud",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": 30,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false,
        "overwrite.cli.url": "http:\/\/firstcloud.dyndns.de",
        "debug": false,
        "enabledPreviewProviders": {
            "0": "OC\\Preview\\PNG",
            "1": "OC\\Preview\\JPEG",
            "2": "OC\\Preview\\GIF",
            "11": "OC\\Preview\\Illustrator",
            "12": "OC\\Preview\\Postscript",
            "13": "OC\\Preview\\Photoshop",
            "14": "OC\\Preview\\TIFF"
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "default_language": "de",
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "calendar",
            "documents",
            "joplin",
            "ocdownloader",
            "unsplash"
        ],
        "has_rebuilt_cache": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE"
    }
}

```
</details>

**Are you using external storage, if yes which one (currently not supported by ocDownloader):** local/smb/sftp/...

**Are you using encryption (currently not supported by ocDownloader):** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
  There are no commands defined in the "ldap" namespace.

```
</details>

#### ocDownloader configuration:

**Which downloader are you using:** Aria2

**Do you use a proxy:** Yes

**Which protocols do you allow**: FTP/HTTP/Bittorrent/Youtube

#### Aria2c configuration (remove if not used):

**Which command line/configuration options are you using:** /usr/local/bin/youtube-dl

##### Aria2c error log
<details>
<summary>Aria2c log file (set the log level to debug by using --log-level=debug)</summary>

```
Insert your Aria2c error log here
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/ocdownloader/releases/tag/1.7.11, thanks for your help!
