### ISSUE TITLE
Support NC 22

### ISSUE THREAD

**Issue by z0ow** [e-alfred/ocdownloader#213]
the current latest version makes NC22 crash because it uses some deprecated functions (via https://github.com/nextcloud/server/issues/27868)

**Comment by thoscut** [comment]
Looks like @weeman1337 already did some work on migrating to the new API.

**Comment by weeman1337** [comment]
A PR with a possible solution has been opened by me 4 month ago #204

**Comment by dawid-woitaschek** [comment]
Welp... I thought, that my NC 22 could download torrents with the ocDownloader...
But nada, aria2 won't work AND it's crashing at least the NC settings. So it's sadly in the bin again.

Maybe @e-alfred should just check @weeman1337's #204.

**Comment by Happyfeet01** [comment]
Here is the issue I got when I enable ocdownloader.

https://github.com/nextcloud/server/issues/28364#issue-964274747

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/ocdownloader/releases/download/1.7.12/ocdownloader-1.7.12.tar.gz. Special thanks to @weeman1337 for helping out!
