### ISSUE TITLE
Truncate download URL to get only filename out of it

### ISSUE THREAD

**Issue by e-alfred** [e-alfred/ocdownloader#22]
A URL in the format `http://example.com/file.pdf?somerequest=somevalue` should be downloaded as `file.pdf` instead of `file.pdf?somerequest=somevalue`.

**Comment by Nibbels** [comment]
Is this for ARIA or Curl or both?

**Comment by e-alfred** [comment]
I faced the issue it with ARIA2. I will have to test it with Curl to see if it happens there as well.

I think it is related to this issue: https://github.com/e-alfred/ocdownloader/issues/5
