### ISSUE TITLE
Compatibility with NC v23

### ISSUE THREAD

**Issue by schniepp** [e-alfred/ocdownloader#235]
This app is currently not compatible with NC v23.

**Comment by weeman1337** [comment]
Thanks for the report. Sounds like a duplicate of #229 .

PR #230 is merged - waiting for the 1.8 release (ping @e-alfred )

Stand by ;)

**Comment by schniepp** [comment]
> Thanks for the report. Sounds like a duplicate of #229 .
Ooops. I guess #229 was already marked as "closed", but my NC 22 instance still reported the app to be incompatible with v23. That's why I must have only looked in the open issues, but not in the closed issues. Sorry about that. 

> PR #230 is merged - waiting for the 1.8 release (ping @e-alfred )
> 
> Stand by ;)
Wonderful, thank you!

**Comment by e-alfred** [comment]
1.8.0 is now released. Sorry for the delay. Thanks to the work of @weeman1337!
