### ISSUE TITLE
Feature request: selected user can use ocdownloader

### ISSUE THREAD

**Issue by anditsung** [e-alfred/ocdownloader#240]
right now all user can use ocdownloader function
is it possible to add that only selected user can only use that function

**Comment by weeman1337** [comment]
Hi @anditsung can you check if that fits you needs?:  
https://github.com/nextcloud/server/issues/25411#issuecomment-786293469

**Comment by anditsung** [comment]
yes, something like this.
but dont have this option on ocdownloader.
not all apps have this feature?

**Comment by weeman1337** [comment]
This is a Nextcloud feature available for all apps. You can limit the usage to specific groups.

If you go to the apps management, select ocDownloader there should be a checkbox „Limit to groups“.

**Comment by anditsung** [comment]
i see that now
need to add new group and enable it for the limit to groups to show.
thanks
