### ISSUE TITLE
Add NC24 compatibility

### ISSUE THREAD

**Issue by xkill** [e-alfred/ocdownloader#245]
Please, add NC24 compatibility

**Comment by plyaskin** [comment]
Hi,

When it will be able?

**Comment by Wikinaut** [comment]
The app is apparently currently not compatible for Nextcloud 24.

**Comment by weeman1337** [comment]
Hello @e-alfred I am a bit sad about that you didn't pick up the work some people put into [this PR](#247) solving this issue and also migrating some required bits :frowning_face:
