### ISSUE TITLE
Youtube download vs. legal stuff

### ISSUE THREAD

**Issue by Nibbels** [e-alfred/ocdownloader#25]
This is not  really an issue, but for the logs:
https://www.computerbase.de/2017-09/youtube-mp3-org-stream-ripper-offline/
I live in germany and contributing to some software that is able to download supposed-to-be streams might be problematic.
Problematic, if the streamer takes measures that I should not download the video very easy or if the streamer encrypts it.

So I will just follow my current path and only contribute to HTTP / FTP and legal bittorrent downloads.
I write this that nobody wonders about my silence when it comes to upgrading youtube support and similar ;)

This also might be some topic when it comes to getting the app into nextclouds store.

Greetings

**Comment by DJCrashdummy** [comment]
well... just my 2 cents:
this repository is about integrating existing command-line tools into nextcloud (and other clouds) and not about coding for youtube-dl.

**Comment by blackcrack** [comment]
youtube-dl it is integrating in this piece of software and should be maintained..
you can not tell what have thinking Xavier about that ! let the fingerd in thinking away.. a youtube-dl it is good and was and should stay in this software.. *f....*
this for you be dirt 2 cents .. kick it away.. and hold you back in this direction if you not like this, 
then say it open.. damn .. *an bit angry* 
You have not determine what's good or not good ! and via behind the corner it's more dirty..
if you whant help, so help.. or hold you back..
you must not use the youtube-dl !

**Comment by DJCrashdummy** [comment]
@blackcrack please read my comment(s) carefully and don't put words into my mouth!

i just said "THIS repository is about integrating existing command-line tools into *cloud"... - and `youtube-dl` is an existing command-line tool...!

_(and for sure every used pice of software should be maintained, but that's not the point here; rather there: https://youtube-dl.org/)_

**Comment by Nibbels** [comment]
:D sorry, I did not want to bump this topic up to that ..

Just to acknowledge this side of possible problems. I am very carful about such. That is all I wanted  to have stated here.

Greetings

**Comment by blackcrack** [comment]
Nibbels , all okey you be the one who i have to take  thoughtfulness on you ;) *hug*
and maybe have i am something misunderstood ..  this is because i have edit my post and remove it.
best regards
Blacky

**Comment by e-alfred** [comment]
ocDownloader is merely a frontend for a few CLI tools in the sense most Linux/BSD GUI applications are written. It only uses youtube-dl for a few things like getting the real Youtube URL and extracting an *.mp3 from a downloaded file. If youtube-dl is not installed, no downloads from Youtube will work at all anyway.

The person in the link shown did so many things differently compared to this and many many other projects:

- Running a company and earning lots of money using ad revenue
- Doing the conversion on his own server/domain and probably own servers

None of this applies to this project after all. This project gains no money from anyone and it is merely a tool that can be used to do downloads from different locations. Neither does this project host anything for anyone or provide services to anyone.  It is merely a repository with source code and nothing more.
