### ISSUE TITLE
The Plugins for the Browsers ?

### ISSUE THREAD

**Issue by blackcrack** [e-alfred/ocdownloader#3]
Hi,
it is possible for hosting the plugins also, because be clients 
of the NCdownloader for supporting the functionality too.
Maybe find some peoples where helps with for programming further if in the readme stay 
"helping hands and Programmers wanted for this cloud downloader "slave" ;) and his clients
for developing further" for have a open way for creating a small self running community around.

best regards
Blacky

**Comment by e-alfred** [comment]
There are three companion apps for ocDownloader that @DJazzLab created:

- One for Firefox which will stop working in autumn with Firefox 57 (old addon api will be shut down) considered abandoned as it has no future
- One for Chrome which is Webextension based and should be the future for both Chromium-based (Chrome, Opera, Vivaldi) and Firefox-based browsers found here: https://github.com/e-alfred/ocDownloader_ChromeExtension
- A Windows app that can be compiled and works on Windows 8.1/10 found here: https://github.com/e-alfred/ocDownloader_WindowsDesktop

I forked both of them if somebody is interested to work on them. They mostly work, but the browser extensions cannot download Youtube links, for example. If somebody is interested in helping out, I would welcome that!

**Comment by blackcrack** [comment]
cool :)
thy for the hint :)
