### ISSUE TITLE
Le GID est nul ! Est-ce qu'Aria2c est démarré en mode daemon ?

### ISSUE THREAD

**Issue by Larsene** [e-alfred/ocdownloader#38]
After the installation on NextCloudPi 12.03RC2 through the app' store, i got the message 

Le GID est nul ! Est-ce qu'Aria2c est démarré en mode daemon ?

and ocdownloader is not working.

**Comment by peshane** [comment]
Hi,
Does aria2c daemon is launched (with your http user) ?

**Comment by e-alfred** [comment]
Well, did you follow the information in the readme on how to set up Aria2c? It has to be installed and run with the options mentioned, otherwise it won't work. If you can't install Aria2c, you could use Curl but you have to make some files executable before you can use it.

**Comment by e-alfred** [comment]
Please set up Aria2c correctly or use Curl if Aria2c is not available. if you get any errors that aren't covered here or anywhere else, please file a bug report with all the necessary information.

**Comment by tharga8616** [comment]
Before you run this command:
`sudo -u www-data aria2c --enable-rpc --rpc-allow-origin-all -c -D --log=/var/log/aria2.log --check-certificate=false --save-session=/var/local/aria2c.sess --save-session-interval=2 --continue=true --input-file=/var/local/aria2c.sess --rpc-save-upload-metadata=true --force-save=true --log-level=warn`

make sure that the log owner is www-data

`chown www-data:www-data /var/log/aria2.log`
