### ISSUE TITLE
HTTP Output filename permissions

### ISSUE THREAD

**Issue by Kille250** [e-alfred/ocdownloader#40]
It's saving the files wrong. If i run Aria2c with sudo -u unkn0wn the deamon doesn't start. I don't know how to fix this.

**Comment by e-alfred** [comment]
i think you have mixed in multiple things into here.

- If Aria2c doesn't start, you can try to start it on the CLI without the -D option so it doesn't run as a daemon. It should show you any error that might occur.
- Aria2c has to run as the same user your webserver runs. This is www-data on Debian/Ubuntu and httpd on Redhat/Centos or something else depending on your distribution/setup. If it runs as another user, the files created by Aria2c belong to the wrong user and managing the files inside Nextcloud wouldn't work correctly.
- If you have a problem with the new option to set a custom output filename, then please provide more information on what you did/your environment/etc.

**Comment by e-alfred** [comment]
Well. as there was no reply I would like to close this. Feel free to create a more specific bug report with more information if you find a bug.
