### ISSUE TITLE
Mobile View in FFox 0 Visual Glitches

### ISSUE THREAD

**Issue by returntrip** [e-alfred/ocdownloader#43]
Posting a screenshot from the mobile vie w in FFox 55.0.2 on Android. Please note the visual glitches with formatting:

![image](https://user-images.githubusercontent.com/14056122/30813806-b6ebd2fa-a20e-11e7-8201-9f251a697d8a.png)

**Comment by e-alfred** [comment]
Should be fixed with https://github.com/e-alfred/ocdownloader/commit/b3463810e4a11dafeebb040138d7ffd55374a2c1.
