### ISSUE TITLE
Curl download does not work - Solved

### ISSUE THREAD

**Issue by GAS85** [e-alfred/ocdownloader#50]
Hallo,
 since installation I have no ARIA and would like to use CURL. But App shows always "using ARIA2" and "GID is 'null'" if hitting download button. How to force is to use CURL?
System is:
Ubuntu 16.04
Nextcloud 12.03
Curl
ocdownloader is fresh installed from the Store
```
# php -m | grep curl
curl
# whereis curl
curl: /usr/bin/curl
# ls -la SERVER/
total 20
drwxr-xr-x  2 www-data www-data 4096 Oct 25 11:00 .
drwxr-xr-x 11 www-data www-data 4096 Oct 25 11:00 ..
-rwxr-xr-x  1 www-data www-data 4308 Oct 25 11:00 fallback.php
-rwxr-xr-x  1 www-data www-data  150 Oct 25 11:00 fallback.sh
```
![image](https://user-images.githubusercontent.com/6813635/32048356-89d1dffa-ba49-11e7-8a4a-4425cc69e8c4.png)

**Comment by GAS85** [comment]
To change Settings, please go to http(s)://yourserver/nextcloud/index.php/settings/admin/additional and update it... my God! This should be in Readme:)

**Comment by e-alfred** [comment]
@GAS85 Yes, it has to be set manually in the admin settings. You can create a pull request with more information/screenshots in the readme, if you like.
