### ISSUE TITLE
YouTube download error : Unable to retrieve true YouTube video URL

### ISSUE THREAD

**Issue by liuxiao1998** [e-alfred/ocdownloader#53]
I paste the url: https://www.youtube.com/watch?v=1o7KjjFgiCo  
And it alerts that: Unable to retrieve true YouTube video URL

**Comment by e-alfred** [comment]
Did you follow the installation manual here and install youtube-dl? ocDownloader cannot download files from Youtube without it. The requirements are documented here:

https://github.com/e-alfred/ocdownloader#youtube-dl-installation
