### ISSUE TITLE
CSS is broken in NC 13

### ISSUE THREAD

**Issue by Happyfeet01** [e-alfred/ocdownloader#55]
Hello,

i upgraded my cloud to NC13, but it seems that the Layout is brocken.
Can you fix it?

![ocdownlaoder_nc13](https://user-images.githubusercontent.com/3295104/34325837-03f4b3de-e89e-11e7-9c51-e7d0b28e711c.PNG)

**Comment by e-alfred** [comment]
Solved by https://github.com/e-alfred/ocdownloader/pull/56 (thanks @Lokarde), I will release a new version on the app store soon.
