### ISSUE TITLE
Class OC_OCS_Result not found

### ISSUE THREAD

**Issue by tacruc** [e-alfred/ocdownloader#59]
Tried to downlaod a file today. With the Firefox plugin I get some log entries like this:
`Error: Class 'OC_OCS_Result' not found at /var/www/nextcloud/apps/ocdownloader/appinfo/routes.php#90`
and the download is not working.

Trying the same link with the app Web interface I get

```
Undefined index: result at /var/www/nextcloud/apps/ocdownloader/controller/httpdownloader.php#195 
Undefined index: result at /var/www/nextcloud/apps/ocdownloader/controller/httpdownloader.php#182 
Undefined index: result at /var/www/nextcloud/apps/ocdownloader/controller/httpdownloader.php#181 
Undefined index: result at /var/www/nextcloud/apps/ocdownloader/controller/httpdownloader.php#176
```

I was thinking about a broken install so I disabled and removed the app and reenabled it again. But the Problem is still there.

I'm using **nextcloud 13RC2**

Any idea what is going wrong here?

**Comment by e-alfred** [comment]
This seems to be two separate errors as far as I can see.

The external API for extensions should work now after fixing it here: https://github.com/e-alfred/ocdownloader/commit/4ccd063bef5106b9d7a3e3b55958f1cbe92820f6 I will upload a new release soon, as a quick fix you can change the lines in the file manually.

The other errors caused downloading from the webinterface seem odd to me. Which downloader do you use? Curl or Aria2? Can you share a demo link which doesn't work?

**Comment by tacruc** [comment]
I'm using cUrl tried to download https://www.freecadweb.org/wiki/Download  and there the 64bit windows build.

**Comment by e-alfred** [comment]
I tested it further with the latest ocDownloader using Curl on Ubuntu 14.04 with PHP 7.0 with the download link you provided, but I couldn't reproduce it. Did you set the files in the /SERVER directory to executable? This is a requirement to use the Curl downloader with ocDownloader.

**Comment by tacruc** [comment]
Wired the files in ther server was not executable changed it but still got the same error. But the Download entries with the GID are in the database. 
![grafik](https://user-images.githubusercontent.com/402891/35482511-a1341a7a-045c-11e8-90d7-ea4795e4f08f.png)
