### ISSUE TITLE
Link to DjazzLabs inside code

### ISSUE THREAD

**Issue by Nibbels** [e-alfred/ocdownloader#6]
https://github.com/e-alfred/ocdownloader/blob/fac43d42e8249ca06f3e9003b5355dd88d491bcb/controller/lib/tools.php#L175

This is still linked to DjazzLabs repository.
We should check if the function is still active and usefull. If it is, we might wanna link this to e-alfred.

**Comment by e-alfred** [comment]
I changed it to this repository and bumped the number in the version file. Thanks for mentioning it!
