### ISSUE TITLE
how to use the ocdownload connect to Aria2 with rpc secret?

### ISSUE THREAD

**Issue by zaglaw** [e-alfred/ocdownloader#60]
doyou have a config panel to set this?

**Comment by zaglaw** [comment]
I try to edit the /controller/lib/aria2.php 
amend the url with token:xxxx
but when I try to down http
it shows me 
no return GID
then I ssh to server 
use ps -aux and netstat 
and try to use aria2ng webui ,and the webui works!
how to fix the egid wrong 
here is the  return
root@nc:/var/snap/nextcloud/current/nextcloud/extra-apps/ocdownloader/controller/lib# netstat -lnpt |grep 6800
tcp        0      0 0.0.0.0:6800            0.0.0.0:*               LISTEN      852/aria2c
tcp6       0      0 :::6800                 :::*                    LISTEN      852/aria2c
root@zaglaw:/var/snap/nextcloud/current/nextcloud/extra-apps/ocdownloader/controller/lib# ps -aux |grep aria2
root       852  0.1  0.5  13096 10100 ?        S    14:48   0:02 aria2c -c /root/.aria2/aria2.conf
root      3705  0.0  0.0  12784   984 pts/0    S+   15:30   0:00 grep aria2
here is the aria2 conf
## '#'开头为注释内容, 选项都有相应的注释说明, 根据需要修改 ##
## 被注释的选项填写的是默认值, 建议在需要修改时再取消注释  ##

## 文件保存相关 ##

# 文件的保存路径(可使用绝对路径或相对路径), 默认: 当前启动位置
dir=/home/disk1/download
# 启用磁盘缓存, 0为禁用缓存, 需1.16以上版本, 默认:16M
#disk-cache=32M
# 文件预分配方式, 能有效降低磁盘碎片, 默认:prealloc
# 预分配所需时间: none < falloc ? trunc < prealloc
# falloc和trunc则需要文件系统和内核支持
# NTFS建议使用falloc, EXT3/4建议trunc, MAC 下需要注释此项
 file-allocation=trunc
# 断点续传
continue=true

## 下载连接相关 ##
# 最大同时下载任务数, 运行时可修改, 默认:5
max-concurrent-downloads=10
# 同一服务器连接数, 添加时可指定, 默认:1
max-connection-per-server=5
# 最小文件分片大小, 添加时可指定, 取值范围1M -1024M, 默认:20M
# 假定size=10M, 文件为20MiB 则使用两个来源下载; 文件为15MiB 则使用一个来源下载
min-split-size=10M
# 单个任务最大线程数, 添加时可指定, 默认:5
split=20
# 整体下载速度限制, 运行时可修改, 默认:0
#max-overall-download-limit=0
# 单个任务下载速度限制, 默认:0
#max-download-limit=5M
# 整体上传速度限制, 运行时可修改, 默认:0
max-overall-upload-limit=1M
# 单个任务上传速度限制, 默认:0
#max-upload-limit=1000
# 禁用IPv6, 默认:false
disable-ipv6=false

## 进度保存相关 ##

# 从会话文件中读取下载任务
input-file=/root/.aria2/aria2.session
# 在Aria2退出时保存`错误/未完成`的下载任务到会话文件
save-session=/root/.aria2/aria2.session
# 定时保存会话, 0为退出时才保存, 需1.16.1以上版本, 默认:0
save-session-interval=60

## RPC相关设置 ##

# 启用RPC, 默认:false
enable-rpc=true
# 允许所有来源, 默认:false
rpc-allow-origin-all=true
# 允许非外部访问, 默认:false
rpc-listen-all=true
# 事件轮询方式, 取值:[epoll, kqueue, port, poll, select], 不同系统默认值不同
#event-poll=select
# RPC监听端口, 端口被占用时可以修改, 默认:6800
rpc-listen-port=6800
# 设置的RPC授权令牌, v1.18.4新增功能, 取代 --rpc-user 和 --rpc-passwd 选项
rpc-secret=doub.bid
# 设置的RPC访问用户名, 此选项新版已废弃, 建议改用 --rpc-secret 选项
#rpc-user=<USER>
# 设置的RPC访问密码, 此选项新版已废弃, 建议改用 --rpc-secret 选项
#rpc-passwd=<PASSWD>
# 是否启用 RPC 服务的 SSL/TLS 加密,
# 启用加密后 RPC 服务需要使用 https 或者 wss 协议连接
#rpc-secure=true
# 在 RPC 服务中启用 SSL/TLS 加密时的证书文件(.pem/.crt)
#rpc-certificate=/root/xxx.pem
# 在 RPC 服务中启用 SSL/TLS 加密时的私钥文件(.key)
#rpc-private-key=/root/xxx.key

## BT/PT下载相关 ##

# 当下载的是一个种子(以.torrent结尾)时, 自动开始BT任务, 默认:true
follow-torrent=true
# BT监听端口, 当端口被屏蔽时使用, 默认:6881-6999
listen-port=51413
# 单个种子最大连接数, 默认:55
bt-max-peers=128
# 打开DHT功能, PT需要禁用, 默认:true
enable-dht=true
# 打开IPv6 DHT功能, PT需要禁用
#enable-dht6=false
# DHT网络监听端口, 默认:6881-6999
#dht-listen-port=6881-6999
# 本地节点查找, PT需要禁用, 默认:false
.................
check-certificate=false

**Comment by e-alfred** [comment]
Currently, it is not implemented. What does the Aria2c log show if you manually add the RPC token? Please increase the log level to debug to show anything meaningful.

**Comment by ctermiii** [comment]
I found this issus too.
ocdownloader dosnt support aria2c  rpc-secret.

**Comment by Happyfeet01** [comment]
Can you add an support for this @e-alfred?

**Comment by LostInsight** [comment]
Adding the token before all the Args will make aria2.php to work but ocdownloader still won't work. Please implement!

simplely add

` array_unshift($Args,"token:YourRpcSecret");`
to aria2.php after args and make it

```
$Args =(strcmp($Name, 'addTorrent') == 0 ? self::rebuildTorrentArgs($Args) : self::rebuildArgs($Args));
array_unshift($Args,"token:YourRpcSecret");
```

**Comment by dragonandy** [comment]
Any updates?

**Comment by Happyfeet01** [comment]
Any news?

**Comment by aurelien-reeves** [comment]
+1 with that feature request.
That would allow more secure use of aria2

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/ocdownloader/pull/164
