### ISSUE TITLE
the link https://raw.githubusercontent.com/e-alfred/ocdownloader/master/appinfo/version  is 404 not found 

### ISSUE THREAD

**Issue by IIIVII** [e-alfred/ocdownloader#63]
the ocdownload is always display update available,I think because of the link https://raw.githubusercontent.com/e-alfred/ocdownloader/master/appinfo/version is 404 not found,please fix it.

**Comment by e-alfred** [comment]
I fixed it for now but I will eventually remove the update message because nowadays the App Store works pretty well for updates/notifications.
