### ISSUE TITLE
Magnet Links

### ISSUE THREAD

**Issue by Luticus** [e-alfred/ocdownloader#64]
Any chance the torrent client will support magnet links at some point so we don't have to download the .torrent and then upload it to the ocDownloader?

**Comment by blackcrack** [comment]
👍 
magnet would be cool .. :)

**Comment by e-alfred** [comment]
Please don't open duplicate issues for features. There is another feature request already:

https://github.com/e-alfred/ocdownloader/issues/13

**Comment by Luticus** [comment]
Apologies, Searched for 'magnet' in the search bar for issues and for some reason nothing came up.  Anyhow, glad it's already on the radar.

Thanks
