### ISSUE TITLE
Nextcloud 14 will drop OCP\DB support 

### ISSUE THREAD

**Issue by rullzer** [e-alfred/ocdownloader#73]
Hi @e-alfred, OCP\DB is deprecated since version 8.1 and will run into the 3 year deprecation time soon. With the upcoming Nextcloud 14 this will not be available anymore. We highly encourage you to move over from to the \OCP\IDBConnection. Preferably even to the IQueryBuilder. If you need help with the migration please reach out to us.

The removal PR: https://github.com/nextcloud/server/pull/8985

**Comment by MorrisJobke** [comment]
Also ref https://github.com/nextcloud/server/issues/7827

**Comment by e-alfred** [comment]
Do you have some good examples on how to implement this? I already checked the doc (https://docs.nextcloud.com/server/13/developer_manual/app/database.html?highlight=idbconnection and ) but there is no good example of how to implement `IDBConnection` in `Application.php`.

**Comment by rullzer** [comment]
See https://github.com/e-alfred/ocdownloader/pull/74 for a small example

**Comment by e-alfred** [comment]
@rullzer Thanks for your help! The abstraction will probably also solve https://github.com/e-alfred/ocdownloader/issues/72 and https://github.com/e-alfred/ocdownloader/issues/67 and https://github.com/e-alfred/ocdownloader/issues/65 as well as other database related problems/bugs.

**Comment by MorrisJobke** [comment]
@e-alfred Just want to check if there is anything we can help you with? Maybe answer some questions or give some reviews of PRs ;)

**Comment by e-alfred** [comment]
@MorrisJobke Thanks for your help, there are indeed a few SQL queries that are more difficult to convert to Querybuilder:

https://github.com/e-alfred/ocdownloader/blob/907902fd10c6a8e1f0c6ed277b2fee4550edb09c/controller/lib/tools.php#L130

https://github.com/e-alfred/ocdownloader/blob/907902fd10c6a8e1f0c6ed277b2fee4550edb09c/controller/queue.php#L71

I also created a PR with all the changes, maybe you can help me with a thorough review: https://github.com/e-alfred/ocdownloader/pull/79

**Comment by nickvergessen** [comment]
For the queue.php
Replace
https://github.com/e-alfred/ocdownloader/blob/907902fd10c6a8e1f0c6ed277b2fee4550edb09c/controller/queue.php#L68-L139

with:
```php
				$query = \OC::$server->getDatabaseConnection()->getQueryBuilder();
				$query->select('*')
					->from('ocdownloader_queue')
					->where($query->expr()->eq('uid', $query->createNamedParameter($this->CurrentUID)))
					->orderBy('timestamp', 'asc');

				switch ($_POST['VIEW']) {
					case 'completes':
						$query->andWhere($query->expr()->eq('status', $query->createNamedParameter(0)))
							->andWhere($query->expr()->in('is_cleaned', $query->createNamedParameter([0, 1], IQueryBuilder::PARAM_INT_ARRAY)));
						break;
					case 'removed':
						$query->andWhere($query->expr()->eq('status', $query->createNamedParameter(4)))
							->andWhere($query->expr()->in('is_cleaned', $query->createNamedParameter([0, 1], IQueryBuilder::PARAM_INT_ARRAY)));
						break;
					case 'actives':
						$query->andWhere($query->expr()->eq('status', $query->createNamedParameter(1)))
							->andWhere($query->expr()->in('is_cleaned', $query->createNamedParameter([0, 1], IQueryBuilder::PARAM_INT_ARRAY)));
						break;
					case 'stopped':
						$query->andWhere($query->expr()->eq('status', $query->createNamedParameter(3)))
							->andWhere($query->expr()->in('is_cleaned', $query->createNamedParameter([0, 1], IQueryBuilder::PARAM_INT_ARRAY)));
						break;
					case 'waitings':
						$query->andWhere($query->expr()->eq('status', $query->createNamedParameter(2)))
							->andWhere($query->expr()->in('is_cleaned', $query->createNamedParameter([0, 1], IQueryBuilder::PARAM_INT_ARRAY)));
						break;
					case 'all':
						$query->andWhere($query->expr()->lte('status', $query->createNamedParameter(4)))
							->andWhere($query->expr()->in('is_cleaned', $query->createNamedParameter([0, 1], IQueryBuilder::PARAM_INT_ARRAY)));
						break;
					default: // add view
						$query->andWhere($query->expr()->lte('status', $query->createNamedParameter(3)))
							->andWhere($query->expr()->eq('is_cleaned', $query->createNamedParameter(0)));
						break;
				}
				$Request = $query->execute();

				$Queue = [];
				$DownloadUpdated = false;
				while ($Row = $Request->fetch()) {
```

**Comment by e-alfred** [comment]
@nickvergessen Thanks for your help, greatly appreciated! I will integrate this as soon as possible.

**Comment by e-alfred** [comment]
This is fixed for now, thanks for your help!
