### ISSUE TITLE
Script missing for Bittorrent

### ISSUE THREAD

**Issue by Nibbels** [e-alfred/ocdownloader#8]
There is some upload functionality for ARIA2 and Bittorrent files.

https://github.com/e-alfred/ocdownloader/blob/c4a03359d6e575ea413415a1f711b96ec0534c43/templates/add.php#L14
`script ('files', 'jquery.iframe-transport');`
produces 404 on my system.

`script ('files', 'jquery.fileupload');`
seems to be loaded from 
![screenshot_8](https://user-images.githubusercontent.com/3265671/29742882-8b5b3f16-8a87-11e7-9969-06ce2789da45.png)

Rightnow I cannot test this with missing aria2. Is this upload working without `script ('files', 'jquery.iframe-transport');` nowadays?

Greetings

**Comment by blackcrack** [comment]
nice to see.. but a couple distributions have no aria2 service on running :( 
it is there a possible for use by side of wget an other downloader or so ?
\*carefully question\*duck\*

**Comment by Nibbels** [comment]
ok, at least some upload seem to work with outcommented 
`//script ('files', 'jquery.iframe-transport');`

![screenshot_9](https://user-images.githubusercontent.com/3265671/29743182-8e182912-8a8c-11e7-9dc5-b5c0da25ade6.png)

**Comment by Nibbels** [comment]
I found the uploaded File:
![screenshot_2](https://user-images.githubusercontent.com/3265671/29744396-5aca712e-8aa4-11e7-9682-e83b54ae7df5.png)
HOME>Downloads>Files>Torrent

That is where it is supposed to be!

**Comment by Nibbels** [comment]
Whatever: About "/tmp" -> I cannot find where the upload temps are stored while uploading. I set the --
- upload temp dir
- the session dir
- and the openbase dirs but
while uploading nothing is shown inside. Not in FTP not in SSH using `ls -lsa` (?) Maybe because of too much ram left?

**Comment by Nibbels** [comment]
We can just put a torrent into that folder and choose it instead of copying a link.
I cannot see a special need for 
`script ('files', 'jquery.iframe-transport');`
rightnow so it might be just fine to have the line removed or commented out for now.

**Comment by Nibbels** [comment]
about this /tmp/

Whenever we call "get" as refreshing the files and download list:
$Status = ($this->WhichDownloader == 0 ? Aria2::TellStatus ($AddURI['result']) : CURL::TellStatus ($AddURI['result']));
$Status = ($this->WhichDownloader == 0 ? Aria2::TellStatus ($Row['GID']) : CURL::TellStatus ($Row['GID']));
_or with ARIA2 only:
$Status = Aria2::TellStatus ($_POST['GID']);
$Status = Aria2::TellStatus ($AddTorrent['result']);
$Status = Aria2::TellStatus ($AddURI['result']);_

CURL::TellStatus ($GID) is a real function (_other than ARIA2::TellStatus ($GID) which is only a relay dummy_) 
https://github.com/Nibbels/ocdownloader/blob/master/controller/lib/curl.php#L30

which can only work **if (file_exists ('/tmp/' . $GID . '.curl'))**
So I cannot understand why CURL is  working on me but I cannot see the files...
But I guess we are now in sync of knowledge on this.

**Comment by e-alfred** [comment]
It seems to call jquery.iframe-transport.js which was removed long ago because older Internet explorer versions were dropped by Owncloud/Nextcloud. i don't think we need it because we only support those browsers that Nextcloud supports anyway.

Here is the bug report on that:

https://github.com/nextcloud/server/issues/999
https://github.com/owncloud/core/pull/24081

**Comment by Nibbels** [comment]
https://github.com/e-alfred/ocdownloader/commit/8002cd77b0b0a4003efee1f8d357e860d9c788ac
