### ISSUE TITLE
I have done a traditional Chinese translation so that I can add new authors

### ISSUE THREAD

**Issue by wartw98** [e-alfred/ocdownloader#83]
[zh_TW.zip](https://github.com/e-alfred/ocdownloader/files/2027451/zh_TW.zip)

**Comment by e-alfred** [comment]
Great work! But can you make a pull request so I can merge it? Just fork the repository and add your files, then you can create one.

**Comment by e-alfred** [comment]
Fixed by https://github.com/e-alfred/ocdownloader/pull/84.
