### ISSUE TITLE
Allow downloads from other youtube-dl supported websites

### ISSUE THREAD

**Issue by ThisIsQasim** [e-alfred/ocdownloader#89]
youtube-dl supports downloading videos from a number of different [sites](https://rg3.github.io/youtube-dl/supportedsites.html) and not just youtube. There aren't any additional flags to set you just have to pass the url from a supported website and it starts downloading. However, ocdownloader only allows you to enter a valid youtube url. Can we disable the check for youtube url and allow ocdownloader to download form any of the youtube-dl supported websites?

**Comment by e-alfred** [comment]
Currently youtube-dl is only used to extract the Youtube data URL and then the file is downloaded using Curl or Aria2c respectively. Using youtube-dl directly would solve this problem: https://github.com/e-alfred/ocdownloader/issues/29

**Comment by e-alfred** [comment]
Good news! The current release of ocDownloader allows to download from other sites supported by Youtube-dl like for example Dailymotion and Vimeo. Please test which pages work and which don't so anything that doesn't work can be fixed if possible.

**Comment by ThisIsQasim** [comment]
Just tested with vimeo and it worked great! Thank you so much for this!
