### ISSUE TITLE
Downloaded Torrent Files Aren't Owned by User

### ISSUE THREAD

**Issue by Engineer-of-Stuff** [e-alfred/ocdownloader#91]
### Steps to reproduce
1. Download torrent file.
2. Go to the downloaded files.
3. See the warning "You don't have permission to ..."

### Expected behaviour
Own the files

### Actual behaviour
Don't own the files

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:**  Myslqi

**PHP version:** 7.2

**Nextcloud version:** Newest

**Updated from an older Nextcloud/ownCloud or fresh install:** Both

**Where did you install Nextcloud from:** .tar

#### ocDownloader configuration:

**Which downloader are you using:** Aria2

**Do you use a proxy:** No

**Which protocols do you allow**: FTP/HTTP/Bittorrent/Youtube

**Which command line/configuration options are you using:** Nothing special.

**Comment by e-alfred** [comment]
How do you start Aria2c? You have to run as the same user your webserver runs, i. e. www-data for Ubuntu/Debian for example.

**Comment by Engineer-of-Stuff** [comment]
I start Aria2 with this in my root cron:

`nohup aria2c --daemon --enable-rpc=true --rpc-listen-all --disable-ipv6 > /dev/null 2>&1 &`

**Comment by e-alfred** [comment]
I would like to close this issue for now because it seems to be fixed. If you have any further problem with this issue please leave a comment so I can reopen it.
