### ISSUE TITLE
Compatibility with Nextcloud 14

### ISSUE THREAD

**Issue by juliushaertl** [e-alfred/ocdownloader#94]
Hi,

as you may have already seen, we have entered the beta phase for the release of Nextcloud 14. We try to keep up compatibility with older apps, but in some cases apps need some adjustments to properly work on new Nextcloud releases. With Nextcloud 14 there have been quite some changes in that regard:

You can find a list of all critical changes for app developers and admins at https://github.com/nextcloud/server/issues/7827 You can run `occ app:check-code` to validate that there are no issues with deprecated or private message calls. 

One critical change is the overall restructuring of the main template (https://github.com/nextcloud/server/pull/9982) that might require some adjustments in your app.

We would be very pleased if you can make your app compatible with Nextcloud 14 and release a new version to the app store, so that users can properly test it and the upgrade experience to Nextcloud 14 will be even better than before.

Feel free to ask, if you have any questions regarding making your app compatible with Nextcloud 14. 

Btw. you might have seen that starting August 25, the Nextcloud Conference takes place at the familiar TU Berlin. (https://nextcloud.com/conf/)! We'd like all contributors to be there and that most certainly includes you. You might already have registered but if you haven't - please consider joining us!

Thanks for being part of the Nextcloud community and for all the effort you put into providing this app :rocket:

**Comment by e-alfred** [comment]
Thanks for the heads-up, there are two major roadblocks toward Nextcloud 14 compatibility:

- Rewrite of database queries because of the deprecated and removed `OCP\DB`interface, started already in branches db-rework1 and db-rework.
- Making the UI compatible with the restructured design, not started (yet).

**Comment by Celestialdeath99** [comment]
Is there a time estimate to when this could be released for Nextcloud 14? I could really use this plugin but cannot as my instance is NC 14.

**Comment by e-alfred** [comment]
No ETA, but I am working on moving all the SQL queries to Querybuilder, just as I said above. If you want to help out, it can be done faster probably.

**Comment by Goeste** [comment]
any help with translations needed?

**Comment by e-alfred** [comment]
@Goeste Sure, if you have any new translations of find any mistakes please submit a PR!

@lsnow2017 Here is my PR with all the fixes: https://github.com/e-alfred/ocdownloader/pull/79
I also created a branch with all the changes: https://github.com/e-alfred/ocdownloader/tree/db-rework

I am very happy with any help because I am currently a bit overstretched with other projects.

**Comment by bekon16** [comment]
Hi, any progress with ocdownloader on nextcloud 14? It was most important app for me. Its almost half year since i have to downloading files using putty - pain in the ass. Should i downgrade to nextcloud 13? :(

**Comment by blackcrack** [comment]
hmm, sometimes i use wget in ssh, but if could be possible to have ocdownloader again, 
would it great :)

**Comment by jayarc** [comment]
I have forked the latest db-rework2 branch and tried to fix some of the UI things going on there. I also modified the youtube.php file to use the linux which command to find the proper path, it was failing for me to get the Youtube URL because it wasn't getting the youtube-dl path right.

To use the fork on NC 14+ issue this command inside your nextcloud apps directory:
git clone --single-branch --branch nc-14 https://github.com/jayarc/ocdownloader.git

**Comment by bugsyb** [comment]
@jayarc - many thanks for that.
I've tried it on 14.0.4 stable. Once app is enabled (from CLI) and opened it unfortunately raises below message. 
Had to disable it as couldn't even open generic settings page.
Maybe I'm missing something at my end?

/apps\/ocdownloader\/add","message":{"Exception":"Error","Message":"Class 'OCP\\DB' not found","Code":0,"Trace":[{"file":"\/nextcloud\/apps\/ocdownloader\/controller\/lib\/tools.php","line":187,"function":"getValue","class":"OCA\\ocDownloader\\Controller\\Lib\\Settings","type":"->","args":[]},{"file":"\/nextcloud\/apps\/ocdownloader\/controller\/index.php","line":47,"function":"canCheckForUpdate","class":"OCA\\ocDownloader\\Controller\\Lib\\Tools","type":"::","args":[]},{"file":"\/nextcloud\/apps\/ocdownloader\/appinfo\/application.php","line":44,"function":"__construct","class":"OCA\\ocDownloader\\Controller\\Index","type":"->","args":["ocdownloader",{"__class__":"OC\\AppFramework\\Http\\Request"},"mypooruser",{"__class__":"OC\\L10N\\L10N"}]},{"file":"\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":118,"function":"OCA\\ocDownloader\\AppInfo\\{closure}","class":"OCA\\ocDownloader\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":117,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["IndexController"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":446,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["IndexController"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":424,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["IndexController"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/App.php","line":95,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["IndexController"]},{"file":"\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["IndexController","Add","*** sensitive parameter replaced ***",{"_route":"ocdownloader.Index.Add"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"ocdownloader.Index.Add"}]},{"file":"\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"ocdownloader.Index.Add"}]},{"file":"\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/ocdownloader\/add"]},{"file":"\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/nextcloud\/apps\/ocdownloader\/controller\/lib\/settings.php","Line":80,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"14.0.4.2"}

**Comment by bekon16** [comment]
I have this error:
`Error: Call to undefined function style()
/var/www/nextcloud/lib/private/legacy/app.php - line 622:

include()

/var/www/nextcloud/lib/private/Settings/Manager.php - line 365:

OC_App::getForms("personal")

/var/www/nextcloud/settings/Controller/CommonSettingsTrait.php - line 93:

OC\Settings\Manager->getPersonalSections()

/var/www/nextcloud/settings/Controller/CommonSettingsTrait.php - line 46:

OC\Settings\Controller\PersonalSettingsController->formatPersonalSections("personal", "personal-info")

/var/www/nextcloud/settings/Controller/CommonSettingsTrait.php - line 125:

OC\Settings\Controller\PersonalSettingsController->getNavigationParameters("personal", "personal-info")

/var/www/nextcloud/settings/Controller/PersonalSettingsController.php - line 57:

OC\Settings\Controller\PersonalSettingsController->getIndexResponse("personal", "personal-info")

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:

OC\Settings\Controller\PersonalSettingsController->index("personal-info")

/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "index")

/var/www/nextcloud/lib/private/AppFramework/App.php - line 118:

OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "index")

/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

OC\AppFramework\App::main("OC\\Setting ... r", "index", OC\AppFramew ... {}, { section: " ... "})


OC\AppFramework\Routing\RouteActionHandler->__invoke({ section: " ... "})

/var/www/nextcloud/lib/private/Route/Router.php - line 297:

call_user_func(OC\AppFramew ... {}, { section: " ... "})

/var/www/nextcloud/lib/base.php - line 987:

OC\Route\Router->match("/settings/user")

/var/www/nextcloud/index.php - line 42:

OC::handleRequest()`

**Comment by Goeste** [comment]
I can second @bugsyb error: [#108](https://github.com/e-alfred/ocdownloader/issues/108#issuecomment-450896492)

**Comment by e-alfred** [comment]
I created a new testing release with all the UI fixes by @jayarc that is compatible with NC14+:

https://github.com/e-alfred/ocdownloader/releases/tag/1.6.0-Alpha1

Currently there are two things that don't work:

- Personal settings
- API for extensions

**Comment by bekon16** [comment]
Hi, not only Personal settings are not working. Also admin settings page is unavailable so without this (admin page settings) this app is useless, but overall good job.
I'm wating for version with working settings page.

**Comment by e-alfred** [comment]
@bekon16 I created a new release that should fix the personal settings problem for now.

**Comment by jtibrewala** [comment]
Can you please repost the link to the release?

**Comment by e-alfred** [comment]
Just go to the releases page on Gihthub or in the Nextcloud App Store:

https://github.com/e-alfred/ocdownloader/releases/tag/1.6.0-Alpha2

**Comment by bekon16** [comment]
@e-alfred Thank you very much! It works! I appreciate very much!
There are still issues to fix:
- In settings i can't set download folder. There is some "loading" icon which does not disappear. I can type new destination folder but it remember previous setting.
- For a while i was able to see additional settings for ocDownloader on admin page (cURL, Aria2 and other options), after refresh (i didn't catch exactly this moment) settings disappeared

**Comment by bekon16** [comment]
Hi, any progress (update to version 15 and erroe with destination folder)?

**Comment by e-alfred** [comment]
This is solved so far, for further issues please refer to the existing ones or create a new one if needed.
